network:
  version: 2
  ethernets:
    wlp3s0:
      dhcp4: no
      dhcp6: no

  bridges:
    br0:
      interfaces: [wlp3s0]
      dhcp4: no
      addresses: [192.168.250.0/16]
      gateway4: 192.168.1.1
      nameservers:
        addresses: [127.0.0.53]
        addresses: [192.168.1.1]
