network:
  version: 2
  ethernets:
    ens33:
      dhcp4: no
      dhcp6: no

  bridges:
    br0:
      interfaces: [wlp3s0]
      dhcp4: no
      addresses: [192.168.0.51/24]
      gateway4: 192.168.1.1
      nameservers:
        addresses: [127.0.0.53]
